etcd:
  userName:
  password:
  secret: ABBRE123

mysql:
  dbMysqlUserName: root
  dbMysqlPassword: ABBRE123

mongo:
  dbUserName:             root
  dbPassword: ABBRE123

redis:
  dbUserName:
  dbPassWord: ABBRE123

kafka:
  SASLUserName:
  SASLPassword:

credential:
  minio:
    endpoint: http://1.13.195.235:10005
    accessKeyID: root
    secretAccessKey: ABBRE123

secret: ABBRE123

tokenpolicy:
  accessSecret: "open_im_server" #token生成相关 建议修改
  accessExpire: 90 #token过期时间（天） 默认即可

messageverify:
  friendVerify: false #发送消息是否验证好友关系 false表示不验证好友关系

push:
  getui:
    pushUrl: "https://restapi.getui.com/v2/78yu1EUm6a9Q9NieoVX249"
    masterSecret: "FAXuHviLwb8pMJq3VbKwu4"  #需添加
    appKey: "BeAQquFPNB7Z4sKrvwMSm1"  #需添加
    enable: true  #true启动个推推送

